version: "2"
linters:
  enable:
    - misspell
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - bin
      - dist
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/tedkulp/tix
  exclusions:
    generated: lax
    paths:
      - bin
      - dist
      - third_party$
      - builtin$
      - examples$
