linters:
  enable:
    - gofmt
    # - goimports
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - errcheck
    # - revive

linters-settings:
  goimports:
    local-prefixes: github.com/tedkulp/tix

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
  skip-dirs:
    - bin
    - dist 