version: 2

builds:
  - id: tix
    binary: tix
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/tedkulp/tix/internal/version.Version={{.Version}}
      - -X github.com/tedkulp/tix/internal/version.Commit={{.Commit}}
      - -X github.com/tedkulp/tix/internal/version.Date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    formats:
      - tar.gz
  - id: windows
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    formats:
      - zip
    builds_info:
      group: default
    ids:
      - tix
    allow_different_binary_count: true

nfpms:
  - id: tix
    package_name: tix
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Ted Kulp
    maintainer: Ted Kulp <ted@tedkulp.com>
    homepage: https://github.com/tedkulp/tix
    description: A CLI tool for creating tickets and branches in Git repositories
    license: MIT
    formats:
      - deb
      - rpm

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - repository:
      owner: tedkulp
      name: homebrew-tap
      token: '{{ .Env.HOMEBREW_TOKEN }}'
    directory: Formula
    homepage: https://github.com/tedkulp/tix
    description: A CLI tool for creating tickets and branches in Git repositories
    license: MIT
    test: |
      system "#{bin}/tix --version"
    install: |
      bin.install "tix"
    ids:
      - default 